# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68666085cf16af8887dc5b7ac57e8f13951c60e5e701ae8b0d003f5bfdedf36ef01626f70df61c3bddcbd7e05f45dfd17c87011feaefd7e161cdcfcecc27c839

test:
  secret_key_base: cc2a2990a98677f417ccd4ab95a06abb50f7529a5319b48befe054ca1993358ffe4c4cfca80ce6d8bda68d508843ea82f6d6780c469769ea034767616dd2d517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
